"""Script to generate all starter notebooks for the assignment."""
import json, os

NOTEBOOKS = {}

# ─── Notebook 1: EDA Image ───────────────────────────────────────

NOTEBOOKS["01_eda_image.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 📊 EDA – Image Dataset (CIFAR-100)\n\n**CO5085 – Assignment 1**\n\nMục đích: Khám phá và hiểu tập dữ liệu ảnh."],"id":"01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom torchvision import datasets, transforms\nfrom collections import Counter\n\nprint('Libraries loaded ✅')"],"id":"02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Download Dataset"],"id":"03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["train_ds = datasets.CIFAR100(root='../data/image', train=True,  download=True, transform=transforms.ToTensor())\ntest_ds  = datasets.CIFAR100(root='../data/image', train=False, download=True, transform=transforms.ToTensor())\nprint(f'Train size: {len(train_ds)} | Test size: {len(test_ds)}')\nprint(f'Classes (first 10): {train_ds.classes[:10]}')\nprint(f'Image shape: {train_ds[0][0].shape}')"],"id":"04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Class Distribution"],"id":"05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["labels = [y for _, y in train_ds]\ncounts = Counter(labels)\nplt.figure(figsize=(20, 4))\nplt.bar(range(100), [counts[i] for i in range(100)], color='steelblue')\nplt.title('CIFAR-100 – Class Distribution (Train)')\nplt.xlabel('Class ID')\nplt.ylabel('Count')\nplt.tight_layout()\nplt.savefig('../results/cifar100_class_dist.png', dpi=150)\nplt.show()\nprint(f'Min samples per class: {min(counts.values())} | Max: {max(counts.values())}')"],"id":"06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Sample Images"],"id":"07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import torchvision\nimport torch\n\nfig, axes = plt.subplots(4, 8, figsize=(16, 8))\nfor i, ax in enumerate(axes.flat):\n    img, label = train_ds[i * 37 % len(train_ds)]\n    ax.imshow(img.permute(1, 2, 0).clamp(0, 1))\n    ax.set_title(train_ds.classes[label], fontsize=7)\n    ax.axis('off')\nplt.suptitle('CIFAR-100 – Sample Images', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.savefig('../results/cifar100_samples.png', dpi=150)\nplt.show()"],"id":"08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Pixel Statistics"],"id":"09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["# Compute channel-wise mean and std (on a subset for speed)\nsubset = torch.stack([train_ds[i][0] for i in range(0, min(5000, len(train_ds)), 5)])\nmeans = subset.mean(dim=[0, 2, 3])\nstds  = subset.std(dim=[0, 2, 3])\nprint(f'Mean: {means.tolist()}')\nprint(f'Std:  {stds.tolist()}')"],"id":"10"},
  {"cell_type":"markdown","metadata":{},"source":["## 5. Augmentation Preview"],"id":"11"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from torchvision import transforms\nfrom datasets import get_image_transforms\n\nbase_img = transforms.ToPILImage()(train_ds[0][0])\naug = get_image_transforms(train=True, img_size=32)\n\nfig, axes = plt.subplots(2, 5, figsize=(14, 5))\nfor i, ax in enumerate(axes.flat):\n    ax.imshow(aug(base_img).permute(1, 2, 0).clamp(0, 1))\n    ax.set_title(f'Aug #{i+1}', fontsize=9)\n    ax.axis('off')\nplt.suptitle('Augmentation Examples', fontsize=13)\nplt.tight_layout()\nplt.savefig('../results/augmentation_preview.png', dpi=150)\nplt.show()"],"id":"12"},
 ]
}

# ─── Notebook 2: EDA Text ────────────────────────────────────────

NOTEBOOKS["02_eda_text.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 📊 EDA – Text Dataset (20 Newsgroups)\n\n**CO5085 – Assignment 1**\n\nMục đích: Khám phá và phân tích tập dữ liệu văn bản."],"id":"t01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.datasets import fetch_20newsgroups\nfrom collections import Counter\nprint('Libraries loaded ✅')"],"id":"t02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Load Dataset"],"id":"t03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["train_raw = fetch_20newsgroups(subset='train', remove=('headers','footers','quotes'))\ntest_raw  = fetch_20newsgroups(subset='test',  remove=('headers','footers','quotes'))\nprint(f'Train: {len(train_raw.data)} | Test: {len(test_raw.data)}')\nprint(f'Categories: {train_raw.target_names}')"],"id":"t04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Class Distribution"],"id":"t05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["counts = Counter(train_raw.target)\nclass_names = train_raw.target_names\nplt.figure(figsize=(14, 5))\nplt.bar([class_names[i] for i in sorted(counts)], [counts[i] for i in sorted(counts)], color='coral')\nplt.xticks(rotation=45, ha='right')\nplt.title('20 Newsgroups – Class Distribution')\nplt.tight_layout()\nplt.savefig('../results/newsgroups_class_dist.png', dpi=150)\nplt.show()"],"id":"t06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Text Length Distribution"],"id":"t07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["lengths = [len(text.split()) for text in train_raw.data]\nplt.figure(figsize=(10, 4))\nplt.hist(lengths, bins=50, color='teal', edgecolor='white')\nplt.axvline(np.median(lengths), color='red', linestyle='--', label=f'Median: {np.median(lengths):.0f}')\nplt.title('Distribution of Document Lengths (words)')\nplt.xlabel('Words')\nplt.ylabel('Count')\nplt.legend()\nplt.tight_layout()\nplt.savefig('../results/newsgroups_length_dist.png', dpi=150)\nplt.show()\nprint(f'Mean: {np.mean(lengths):.1f} | Median: {np.median(lengths):.1f} | Max: {max(lengths)}')"],"id":"t08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Sample Documents"],"id":"t09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["for i in range(3):\n    print(f'--- Sample {i+1} | Label: {class_names[train_raw.target[i]]} ---')\n    print(train_raw.data[i][:400])\n    print()"],"id":"t10"},
  {"cell_type":"markdown","metadata":{},"source":["## 5. Tokenization Statistics (DistilBERT)"],"id":"t11"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from transformers import AutoTokenizer\ntokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')\ntoken_lengths = [len(tokenizer.encode(t, truncation=False)) for t in train_raw.data[:2000]]\nprint(f'Token lengths – Mean: {np.mean(token_lengths):.1f} | 95th pct: {np.percentile(token_lengths, 95):.1f}')\nfor threshold in [128, 256, 512]:\n    pct = sum(l <= threshold for l in token_lengths) / len(token_lengths) * 100\n    print(f'  <= {threshold} tokens: {pct:.1f}%')"],"id":"t12"},
 ]
}

# ─── Notebook 3: EDA Multimodal ──────────────────────────────────

NOTEBOOKS["03_eda_multimodal.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 📊 EDA – Multimodal Dataset (CIFAR-100 Superclasses + CLIP)\n\n**CO5085 – Assignment 1**\n\nMục đích: Khám phá tập dữ liệu đa phương thức dùng CIFAR-100 superclasses làm proxy với text prompts tự động."],"id":"mm_e01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport torch, clip\nfrom torchvision import datasets\nimport torchvision.transforms as T\nfrom collections import Counter\nimport os\nos.makedirs('../results', exist_ok=True)\n\nDEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Libraries loaded ✅ | Device: {DEVICE}')"],"id":"mm_e02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Dataset Overview"],"id":"mm_e03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["# CIFAR-100 superclasses (20 groups used as multimodal class labels)\nSUPERCLASSES = [\n    'aquatic mammals', 'fish', 'flowers', 'food containers', 'fruit and vegetables',\n    'household electrical devices', 'household furniture', 'insects', 'large carnivores',\n    'large man-made outdoor things', 'large natural outdoor scenes', 'large omnivores and herbivores',\n    'medium-sized mammals', 'non-insect invertebrates', 'people', 'reptiles',\n    'small mammals', 'trees', 'vehicles 1', 'vehicles 2'\n]\n\ncoarse_labels = [\n    4, 1, 14, 8, 0, 6, 7, 7, 18, 3, 3, 14, 9, 18, 7, 11, 3, 9, 7, 11,\n    6, 11, 5, 10, 7, 6, 13, 15, 3, 15, 0, 11, 1, 10, 12, 14, 16, 9, 11, 5,\n    5, 19, 8, 8, 15, 13, 14, 17, 18, 10, 16, 4, 17, 4, 2, 0, 17, 4, 18, 17,\n    10, 3, 2, 12, 12, 16, 12, 1, 9, 19, 2, 10, 0, 1, 16, 12, 9, 13, 15, 13,\n    16, 19, 2, 4, 6, 19, 5, 5, 8, 19, 18, 1, 2, 15, 6, 0, 17, 8, 14, 13\n]\n\ntrain_ds = datasets.CIFAR100(root='../data/image', train=True, download=True,\n                              transform=T.ToTensor())\ntest_ds  = datasets.CIFAR100(root='../data/image', train=False, download=True,\n                              transform=T.ToTensor())\nprint(f'Train: {len(train_ds)} | Test: {len(test_ds)} | Superclasses: {len(SUPERCLASSES)}')"],"id":"mm_e04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Superclass Distribution"],"id":"mm_e05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["train_coarse = [coarse_labels[y] for _, y in train_ds]\ncounts = Counter(train_coarse)\n\nplt.figure(figsize=(14, 5))\nplt.bar([SUPERCLASSES[i] for i in sorted(counts)], [counts[i] for i in sorted(counts)], color='mediumpurple')\nplt.xticks(rotation=45, ha='right', fontsize=8)\nplt.title('CIFAR-100 Superclass Distribution (Train)')\nplt.ylabel('Count')\nplt.tight_layout()\nplt.savefig('../results/multimodal_superclass_dist.png', dpi=150)\nplt.show()\nprint(f'Samples per superclass – Min: {min(counts.values())} | Max: {max(counts.values())}')"],"id":"mm_e06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Sample Image-Text Pairs"],"id":"mm_e07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["fig, axes = plt.subplots(4, 5, figsize=(15, 12))\nshown = {}\nfor img_t, fine_label in train_ds:\n    sc = coarse_labels[fine_label]\n    if sc not in shown:\n        shown[sc] = (img_t, SUPERCLASSES[sc])\n    if len(shown) == 20:\n        break\n\nfor ax, (sc_idx, (img_t, prompt)) in zip(axes.flat, sorted(shown.items())):\n    ax.imshow(img_t.permute(1, 2, 0).clamp(0, 1))\n    ax.set_title(f'\\'a photo of a {prompt}\\'', fontsize=7, wrap=True)\n    ax.axis('off')\n\nplt.suptitle('Image–Text Pairs (one sample per superclass)', fontsize=13, fontweight='bold')\nplt.tight_layout()\nplt.savefig('../results/multimodal_image_text_pairs.png', dpi=150)\nplt.show()"],"id":"mm_e08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Text Prompt Statistics (CLIP Tokenizer)"],"id":"mm_e09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["# Load CLIP tokenizer (no model weights needed for this)\nmodel_clip, preprocess = clip.load('ViT-B/32', device='cpu')\n\nprompts = [f'a photo of a {sc}' for sc in SUPERCLASSES]\ntoken_lengths = [len(clip.tokenize(p)[0].nonzero()) for p in prompts]\n\nprint('Text prompt token lengths:')\nfor prompt, tlen in zip(prompts, token_lengths):\n    print(f'  [{tlen:2d} tokens] {prompt}')\nprint(f'\\nMean: {np.mean(token_lengths):.1f} | Max: {max(token_lengths)}')"],"id":"mm_e10"},
  {"cell_type":"markdown","metadata":{},"source":["## 5. CLIP Embedding Space Visualization (PCA)"],"id":"mm_e11"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from sklearn.decomposition import PCA\n\n# Encode all 20 text prompts\nwith torch.no_grad():\n    tokens = clip.tokenize(prompts).to('cpu')\n    text_features = model_clip.encode_text(tokens).float().numpy()\n\npca = PCA(n_components=2)\ncoords = pca.fit_transform(text_features)\n\nplt.figure(figsize=(10, 7))\nfor i, (x, y) in enumerate(coords):\n    plt.scatter(x, y, s=80, color='coral')\n    plt.annotate(SUPERCLASSES[i], (x, y), fontsize=8, textcoords='offset points', xytext=(5, 3))\n\nplt.title('CLIP Text Embeddings – PCA (20 Superclass Prompts)')\nplt.xlabel('PC1')\nplt.ylabel('PC2')\nplt.tight_layout()\nplt.savefig('../results/multimodal_clip_text_pca.png', dpi=150)\nplt.show()\nprint(f'Explained variance: PC1={pca.explained_variance_ratio_[0]:.2%}, PC2={pca.explained_variance_ratio_[1]:.2%}')"],"id":"mm_e12"},
 ]
}

# ─── Notebook 4: Image CNN vs ViT ────────────────────────────────

NOTEBOOKS["04_image_cnn_vit.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 🖼️ Image Classification: CNN vs. ViT\n\n**CO5085 – Assignment 1**\n\nSo sánh: **ResNet-50, EfficientNet-B0** (CNN) vs. **ViT-B/16, DeiT-S** (Vision Transformer)"],"id":"img01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport torch\nimport os\nos.makedirs('../results', exist_ok=True)\n\nDEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Device: {DEVICE}')"],"id":"img02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Load Data"],"id":"img03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from datasets import get_cifar100_loaders\ntrain_loader, val_loader, test_loader = get_cifar100_loaders(\n    data_dir='../data/image', batch_size=128)\nprint(f'Train batches: {len(train_loader)} | Val: {len(val_loader)} | Test: {len(test_loader)}')"],"id":"img04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Model 1: ResNet-50 (CNN)"],"id":"img05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_resnet50\nfrom train import train\n\nresnet = get_resnet50(num_classes=100, pretrained=True, freeze_backbone=False)\nhistory_resnet = train(resnet, train_loader, val_loader,\n                       num_epochs=20, lr=1e-3,\n                       device=DEVICE, save_path='../results/resnet50_best.pt',\n                       scheduler_type='cosine')"],"id":"img06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Model 2: EfficientNet-B0 (CNN)"],"id":"img07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_efficientnet_b0\nfrom train import train\n\neffnet = get_efficientnet_b0(num_classes=100, pretrained=True)\nhistory_effnet = train(effnet, train_loader, val_loader,\n                       num_epochs=20, lr=1e-3,\n                       device=DEVICE, save_path='../results/efficientnet_best.pt')"],"id":"img08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Model 3: ViT-B/16"],"id":"img09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_vit_b16\nfrom datasets import get_cifar100_loaders\nfrom torchvision import datasets, transforms\n\n# ViT needs 224x224 – use a transform wrapper\ntrain_loader_vit, val_loader_vit, test_loader_vit = get_cifar100_loaders(\n    data_dir='../data/image', batch_size=32)  # smaller batch for memory\n\nvit_model = get_vit_b16(num_classes=100, pretrained=True)\nhistory_vit = train(vit_model, train_loader_vit, val_loader_vit,\n                    num_epochs=15, lr=2e-5,\n                    device=DEVICE, save_path='../results/vit_b16_best.pt',\n                    scheduler_type='cosine')"],"id":"img10"},
  {"cell_type":"markdown","metadata":{},"source":["## 5. Evaluation & Comparison"],"id":"img11"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from evaluate import get_predictions, compute_metrics, plot_training_curves, compare_models\nimport torch\n\nresults = {}\nfor model_name, model, hist, loader in [\n    ('ResNet-50',   resnet,            history_resnet, test_loader),\n    ('EfficientNet-B0', effnet,        history_effnet, test_loader),\n    ('ViT-B/16',    vit_model,         history_vit,    test_loader_vit),\n]:\n    print(f'\\n=== {model_name} ===')\n    model.load_state_dict(torch.load(f'../results/{model_name.lower().replace(\"-\",\"_\").replace(\"/\",\"_\")}_best.pt', map_location=DEVICE))\n    preds, labels, probs = get_predictions(model, loader, DEVICE)\n    results[model_name] = compute_metrics(preds, labels, verbose=True)\n    plot_training_curves(hist, model_name=model_name, save_path=f'../results/{model_name}_curves.png')"],"id":"img12"},
  {"cell_type":"markdown","metadata":{},"source":["## 6. Overall Comparison Chart"],"id":"img13"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from evaluate import compare_models\ncompare_models(results, metric='accuracy', save_path='../results/image_comparison_acc.png')\ncompare_models(results, metric='f1_macro', save_path='../results/image_comparison_f1.png')"],"id":"img14"},
 ]
}

# ─── Notebook 5: Text RNN vs Transformer ─────────────────────────

NOTEBOOKS["05_text_rnn_transformer.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 📝 Text Classification: RNN vs. Transformer\n\n**CO5085 – Assignment 1**\n\nSo sánh: **BiLSTM, GRU** vs. **DistilBERT, BERT-base**"],"id":"txt01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport torch, os\nos.makedirs('../results', exist_ok=True)\nDEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\nprint(f'Device: {DEVICE}')"],"id":"txt02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Load Data (20 Newsgroups + DistilBERT Tokenizer)"],"id":"txt03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from datasets import get_20newsgroups_loaders\ntrain_loader, val_loader, test_loader, tokenizer, num_classes = get_20newsgroups_loaders(\n    tokenizer_name='distilbert-base-uncased', batch_size=32, max_length=256)\nprint(f'Classes: {num_classes} | Train batches: {len(train_loader)}')"],"id":"txt04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Model 1: DistilBERT (Transformer)"],"id":"txt05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_distilbert\nfrom train import train\n\ndistilbert = get_distilbert(num_classes=num_classes)\nhistory_distilbert = train(distilbert, train_loader, val_loader,\n                           num_epochs=5, lr=2e-5, weight_decay=1e-2,\n                           device=DEVICE, save_path='../results/distilbert_best.pt',\n                           scheduler_type='cosine')"],"id":"txt06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Model 2: BERT-base (Transformer)"],"id":"txt07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_bert\n\n# Use bert tokenizer for separate loader\nfrom datasets import get_20newsgroups_loaders\ntrain_bert, val_bert, test_bert, tok_bert, _ = get_20newsgroups_loaders(\n    tokenizer_name='bert-base-uncased', batch_size=16, max_length=256)\n\nbert_model = get_bert(num_classes=num_classes)\nhistory_bert = train(bert_model, train_bert, val_bert,\n                     num_epochs=5, lr=2e-5,\n                     device=DEVICE, save_path='../results/bert_best.pt')"],"id":"txt08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. BiLSTM (RNN)\n\n> **Note**: BiLSTM uses a simple vocabulary tokenizer instead of WordPiece."],"id":"txt09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["# Build vocab from training data\nfrom sklearn.datasets import fetch_20newsgroups\nfrom sklearn.model_selection import train_test_split\nfrom torch.utils.data import DataLoader, TensorDataset\nimport torch\nimport numpy as np\n\nraw = fetch_20newsgroups(subset='train', remove=('headers','footers','quotes'))\nfrom collections import Counter\nwords = Counter(' '.join(raw.data).lower().split())\nvocab = {w: i+2 for i,(w,_) in enumerate(words.most_common(50000))}\nvocab['<pad>'] = 0\nvocab['<unk>'] = 1\nVOCAB_SIZE = len(vocab)\n\ndef tokenize_simple(texts, max_len=256):\n    result = []\n    for text in texts:\n        ids = [vocab.get(w, 1) for w in text.lower().split()[:max_len]]\n        ids = ids + [0] * (max_len - len(ids))\n        result.append(ids)\n    return torch.tensor(result, dtype=torch.long)\n\ntr_texts, val_texts, tr_labels, val_labels = train_test_split(\n    raw.data, raw.target, test_size=0.15, random_state=42)\n\ntr_X  = tokenize_simple(tr_texts)\nval_X = tokenize_simple(val_texts)\ntest_raw = fetch_20newsgroups(subset='test', remove=('headers','footers','quotes'))\ntest_X = tokenize_simple(test_raw.data)\n\ntrain_lstm = DataLoader(TensorDataset(tr_X, torch.tensor(tr_labels, dtype=torch.long)), batch_size=64, shuffle=True)\nval_lstm   = DataLoader(TensorDataset(val_X, torch.tensor(val_labels, dtype=torch.long)), batch_size=64)\ntest_lstm  = DataLoader(TensorDataset(test_X, torch.tensor(list(test_raw.target), dtype=torch.long)), batch_size=64)\n\nprint(f'Vocab size: {VOCAB_SIZE}')"],"id":"txt10"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import BiLSTMClassifier\nfrom train import train\n\nbilstm = BiLSTMClassifier(vocab_size=VOCAB_SIZE, embed_dim=128, hidden_dim=256,\n                           num_layers=2, num_classes=20, dropout=0.4)\nhistory_bilstm = train(bilstm, train_lstm, val_lstm,\n                       num_epochs=15, lr=1e-3,\n                       device=DEVICE, save_path='../results/bilstm_best.pt')"],"id":"txt11"},
  {"cell_type":"markdown","metadata":{},"source":["## 5. Evaluation & Comparison"],"id":"txt12"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from evaluate import compute_metrics, plot_training_curves, compare_models, get_predictions\n\nresults_text = {}\n\n# DistilBERT\npreds, labels, _ = get_predictions(distilbert, test_loader, DEVICE)\nresults_text['DistilBERT'] = compute_metrics(preds, labels, verbose=True)\nplot_training_curves(history_distilbert, 'DistilBERT', '../results/distilbert_curves.png')\n\n# BERT\npreds, labels, _ = get_predictions(bert_model, test_bert, DEVICE)\nresults_text['BERT-base'] = compute_metrics(preds, labels, verbose=True)\nplot_training_curves(history_bert, 'BERT-base', '../results/bert_curves.png')\n\n# BiLSTM (note: returns plain tensors, not dicts)\nimport torch, torch.nn as nn\nbilstm.eval()\nall_p, all_l = [], []\nwith torch.no_grad():\n    for xb, yb in test_lstm:\n        out = bilstm(xb.to(DEVICE))\n        all_p += out.argmax(-1).cpu().tolist()\n        all_l += yb.tolist()\nimport numpy as np\nresults_text['BiLSTM'] = compute_metrics(np.array(all_p), np.array(all_l), verbose=True)\n\ncompare_models(results_text, metric='accuracy', save_path='../results/text_comparison_acc.png')\ncompare_models(results_text, metric='f1_macro',  save_path='../results/text_comparison_f1.png')"],"id":"txt13"},
 ]
}

# ─── Notebook 6: Multimodal (CLIP) ───────────────────────────────

NOTEBOOKS["06_multimodal_zeroshot_fewshot.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 🔀 Multimodal: Zero-shot vs. Few-shot (CLIP)\n\n**CO5085 – Assignment 1**\n\nDùng CLIP để so sánh zero-shot và few-shot classification trên tập đa phương thức (Flickr30k/COCO subset)."],"id":"mm01"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport torch, clip, numpy as np\nimport matplotlib.pyplot as plt\nfrom PIL import Image\nfrom pathlib import Path\nimport os\nos.makedirs('../results', exist_ok=True)\n\nDEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\nmodel, preprocess = clip.load('ViT-B/32', device=DEVICE)\nprint(f'CLIP loaded on {DEVICE} ✅')"],"id":"mm02"},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Dataset Preparation\n\nSử dụng CIFAR-100 super-classes (20 classes) làm **proxy multimodal dataset** với:\n- Ảnh từ CIFAR-100\n- Text prompt tự động: `'a photo of a {superclass}'`\n\n> Nếu có Flickr30k, thay bằng dataset đó."],"id":"mm03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from torchvision import datasets\nimport torchvision.transforms as T\n\n# CIFAR-100 superclasses (20 groups)\nSUPERCLASSES = [\n    'aquatic mammals', 'fish', 'flowers', 'food containers', 'fruit and vegetables',\n    'household electrical devices', 'household furniture', 'insects', 'large carnivores',\n    'large man-made outdoor things', 'large natural outdoor scenes', 'large omnivores and herbivores',\n    'medium-sized mammals', 'non-insect invertebrates', 'people', 'reptiles',\n    'small mammals', 'trees', 'vehicles 1', 'vehicles 2'\n]\n\n# CIFAR-100 maps each fine class to a superclass\ncoarse_labels = [\n    4, 1, 14, 8, 0, 6, 7, 7, 18, 3, 3, 14, 9, 18, 7, 11, 3, 9, 7, 11,\n    6, 11, 5, 10, 7, 6, 13, 15, 3, 15, 0, 11, 1, 10, 12, 14, 16, 9, 11, 5,\n    5, 19, 8, 8, 15, 13, 14, 17, 18, 10, 16, 4, 17, 4, 2, 0, 17, 4, 18, 17,\n    10, 3, 2, 12, 12, 16, 12, 1, 9, 19, 2, 10, 0, 1, 16, 12, 9, 13, 15, 13,\n    16, 19, 2, 4, 6, 19, 5, 5, 8, 19, 18, 1, 2, 15, 6, 0, 17, 8, 14, 13\n]\n\ntest_ds = datasets.CIFAR100(root='../data/image', train=False, download=True,\n                             transform=T.Compose([T.Resize(224), T.ToTensor()]))\ntest_images = [T.ToPILImage()(test_ds[i][0]) for i in range(500)]\ntest_labels = [coarse_labels[test_ds[i][1]] for i in range(500)]\nprint(f'Test samples: {len(test_images)} | Superclasses: {len(SUPERCLASSES)}')"],"id":"mm04"},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Zero-shot Classification"],"id":"mm05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import CLIPZeroShotClassifier\n\nzero_clf = CLIPZeroShotClassifier(class_names=SUPERCLASSES, device=DEVICE)\nBATCH = 50\nall_preds = []\nfor i in range(0, len(test_images), BATCH):\n    batch_imgs = test_images[i:i+BATCH]\n    _, preds = zero_clf.predict(batch_imgs)\n    all_preds.extend(preds.tolist())\n\nfrom sklearn.metrics import accuracy_score, f1_score\nacc_zs = accuracy_score(test_labels, all_preds)\nf1_zs  = f1_score(test_labels, all_preds, average='macro', zero_division=0)\nprint(f'Zero-shot → Accuracy: {acc_zs:.4f} | F1-Macro: {f1_zs:.4f}')"],"id":"mm06"},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Few-shot Classification (CLIP + Linear Probe)"],"id":"mm07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import CLIPFewShotClassifier\nimport torch.nn as nn\nfrom torch.optim import Adam\n\ndef run_few_shot(k_shots_per_class: int):\n    \"\"\"Train linear probe with k examples per class.\"\"\"\n    clf = CLIPFewShotClassifier(num_classes=len(SUPERCLASSES), device=DEVICE).to(DEVICE)\n\n    # Build few-shot training set\n    from collections import defaultdict\n    class_examples = defaultdict(list)\n    for idx in range(len(test_ds)):\n        img, fine_label = test_ds[idx]\n        coarse = coarse_labels[fine_label]\n        if len(class_examples[coarse]) < k_shots_per_class:\n            class_examples[coarse].append(T.ToPILImage()(img))\n    \n    # Extract CLIP features\n    support_imgs, support_labels = [], []\n    for c, imgs in class_examples.items():\n        support_imgs.extend(imgs)\n        support_labels.extend([c] * len(imgs))\n    \n    X_support = clf.encode_images(support_imgs)\n    y_support = torch.tensor(support_labels, dtype=torch.long).to(DEVICE)\n\n    # Train linear head\n    optimizer = Adam(clf.classifier.parameters(), lr=1e-2)\n    criterion = nn.CrossEntropyLoss()\n    for _ in range(200):\n        optimizer.zero_grad()\n        logits = clf.classifier(X_support)\n        loss = criterion(logits, y_support)\n        loss.backward()\n        optimizer.step()\n\n    # Evaluate\n    clf.eval()\n    test_feats = clf.encode_images(test_images)\n    with torch.no_grad():\n        logits = clf.classifier(test_feats)\n        preds = logits.argmax(-1).cpu().numpy()\n\n    acc = accuracy_score(test_labels, preds)\n    f1  = f1_score(test_labels, preds, average='macro', zero_division=0)\n    print(f'  {k_shots_per_class}-shot → Acc: {acc:.4f}, F1: {f1:.4f}')\n    return acc, f1\n\nresults_mm = {'Zero-shot': {'accuracy': acc_zs, 'f1_macro': f1_zs}}\nfor k in [1, 5, 10, 20]:\n    acc, f1 = run_few_shot(k)\n    results_mm[f'{k}-shot'] = {'accuracy': acc, 'f1_macro': f1}"],"id":"mm08"},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Comparison Chart"],"id":"mm09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from evaluate import compare_models\ncompare_models(results_mm, metric='accuracy', save_path='../results/multimodal_comparison_acc.png')"],"id":"mm10"},
 ]
}

# ─── Notebook 7: Extensions ──────────────────────────────────────

NOTEBOOKS["07_extensions.ipynb"] = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
               "language_info": {"name": "python", "version": "3.10.0"}},
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# 🔬 Extensions\n\n**CO5085 – Assignment 1** | Phần mở rộng (40% điểm)\n\nBao gồm:\n1. Grad-CAM Visualization (CNN)\n2. Attention Map Visualization (ViT)\n3. Error Analysis\n4. Fine-tune Strategy Comparison\n5. Demo App (Gradio)"],"id":"ext01"},
  {"cell_type":"markdown","metadata":{},"source":["## Extension 1: Grad-CAM (CNN – ResNet-50)"],"id":"ext02"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import sys\nsys.path.append('../src')\nimport torch\nfrom torchvision import datasets, transforms\nfrom PIL import Image\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nDEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n\nfrom models import get_resnet50\nresnet = get_resnet50(num_classes=100, pretrained=True)\nresnet.load_state_dict(torch.load('../results/resnet50_best.pt', map_location=DEVICE))\nresnet = resnet.to(DEVICE).eval()"],"id":"ext03"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["try:\n    from pytorch_grad_cam import GradCAM\n    from pytorch_grad_cam.utils.image import show_cam_on_image\n    from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget\nexcept ImportError:\n    import subprocess\n    subprocess.run(['pip', 'install', 'grad-cam'], check=True)\n    from pytorch_grad_cam import GradCAM\n    from pytorch_grad_cam.utils.image import show_cam_on_image\n    from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget\n\ntest_ds = datasets.CIFAR100(root='../data/image', train=False, download=True,\n                             transform=transforms.Compose([transforms.ToTensor()]))\n\ntf_norm = transforms.Compose([\n    transforms.ToTensor(),\n    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])\n])\n\ntarget_layer = [resnet.layer4[-1]]\ncam = GradCAM(model=resnet, target_layers=target_layer)\n\nfig, axes = plt.subplots(2, 5, figsize=(16, 6))\nfor i, ax in enumerate(axes.flat):\n    img_pil, label = test_ds[i * 200]\n    img_np = img_pil.permute(1,2,0).numpy()\n    input_tensor = tf_norm(transforms.ToPILImage()(img_pil)).unsqueeze(0).to(DEVICE)\n    grayscale_cam = cam(input_tensor=input_tensor, targets=[ClassifierOutputTarget(label)])[0]\n    visualization = show_cam_on_image(img_np, grayscale_cam, use_rgb=True)\n    ax.imshow(visualization)\n    ax.set_title(f'{test_ds.classes[label]}', fontsize=8)\n    ax.axis('off')\nplt.suptitle('Grad-CAM Visualization – ResNet-50 on CIFAR-100', fontsize=13, fontweight='bold')\nplt.tight_layout()\nplt.savefig('../results/gradcam_resnet50.png', dpi=150)\nplt.show()"],"id":"ext04"},
  {"cell_type":"markdown","metadata":{},"source":["## Extension 2: Error Analysis"],"id":"ext05"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from evaluate import get_predictions, plot_confusion_matrix\nfrom datasets import get_cifar100_loaders\n\ntrain_loader, val_loader, test_loader = get_cifar100_loaders(batch_size=128)\npreds, labels, probs = get_predictions(resnet, test_loader, DEVICE)\n\n# Top-5 misclassified classes\nimport numpy as np\nwrong_mask = preds != labels\nwrong_preds = preds[wrong_mask]\nwrong_labels = labels[wrong_mask]\n\nfrom collections import Counter\ntop5_errors = Counter(zip(wrong_labels.tolist(), wrong_preds.tolist())).most_common(5)\nprint('Top-5 error pairs (true → predicted):')\nfor (true, pred), count in top5_errors:\n    print(f'  {test_ds.classes[true]:20s} → {test_ds.classes[pred]:20s} : {count} times')\n\nplot_confusion_matrix(preds, labels, test_ds.classes,\n                       save_path='../results/confusion_matrix_resnet50.png', figsize=(18, 15))"],"id":"ext06"},
  {"cell_type":"markdown","metadata":{},"source":["## Extension 3: Fine-tune Strategy Comparison"],"id":"ext07"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["from models import get_resnet50\nfrom train import train\nfrom datasets import get_cifar100_loaders\n\ntrain_loader, val_loader, _ = get_cifar100_loaders(batch_size=128)\nresults_ft = {}\n\nfor strategy, freeze in [('Freeze Backbone', True), ('Full Fine-tune', False)]:\n    print(f'\\n=== Strategy: {strategy} ===')\n    model = get_resnet50(num_classes=100, pretrained=True, freeze_backbone=freeze)\n    hist = train(model, train_loader, val_loader,\n                 num_epochs=10, lr=1e-3 if freeze else 1e-4,\n                 device=DEVICE, save_path=f'../results/resnet_{strategy.replace(\" \",\"_\")}_best.pt')\n    results_ft[strategy] = {'val_acc_last': hist['val_acc'][-1],\n                             'val_acc_best': max(hist['val_acc'])}"],"id":"ext08"},
  {"cell_type":"markdown","metadata":{},"source":["## Extension 4: Gradio Demo App\n\nSau khi train xong, chạy cell này để khởi động demo app."],"id":"ext09"},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["import gradio as gr\nimport torch\nfrom PIL import Image\nfrom torchvision import transforms\nfrom models import get_resnet50\n\n# Load best model\nbest_model = get_resnet50(num_classes=100, pretrained=False)\nbest_model.load_state_dict(torch.load('../results/resnet50_best.pt', map_location='cpu'))\nbest_model.eval()\n\ntf = transforms.Compose([\n    transforms.Resize(40), transforms.CenterCrop(32), transforms.ToTensor(),\n    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])\n])\n\nfrom torchvision import datasets\nclasses = datasets.CIFAR100(root='../data/image', train=False, download=False).classes\n\ndef predict(img):\n    if img is None: return {}\n    input_t = tf(img).unsqueeze(0)\n    with torch.no_grad():\n        probs = torch.softmax(best_model(input_t), dim=-1)[0]\n    top5 = probs.topk(5)\n    return {classes[i]: float(p) for i, p in zip(top5.indices, top5.values)}\n\ndemo = gr.Interface(\n    fn=predict,\n    inputs=gr.Image(type='pil', label='Upload Image'),\n    outputs=gr.Label(num_top_classes=5, label='Predictions'),\n    title='🖼️ CIFAR-100 Classifier (CO5085)',\n    description='Upload an image to classify it into one of 100 CIFAR-100 categories.',\n)\ndemo.launch(share=True)"],"id":"ext10"},
 ]
}

# ─── Write all notebooks ─────────────────────────────────────────

out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "notebooks")
os.makedirs(out_dir, exist_ok=True)
os.makedirs(os.path.join(os.path.dirname(os.path.abspath(__file__)), "results"), exist_ok=True)
for name, nb in NOTEBOOKS.items():
    path = os.path.join(out_dir, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"Created: {path}")

print("\nAll notebooks created ✅")
